platform :ios, '8.0'

use_frameworks!

target 'AKSwiftAuth0Test' do
    pod 'Lock/Core', '~> 1.16'
    pod 'Lock-Facebook', '~> 2.0' #If you need FB native integration
end

post_install do |installer|
    installer.pods_project.build_configurations.each { |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    }
end